[toolchain]
anchor_version = "0.32.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
kyc_registry = "11111111111111111111111111111111"
transfer_hook = "11111111111111111111111111111111"
vault = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = [
  "programs/kyc_registry",
  "programs/transfer_hook",
  "programs/vault",
]

